/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serialport_PsamSerialPort */

#ifndef _Included_com_serialport_PsamSerialPort
#define _Included_com_serialport_PsamSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serialport_PsamSerialPort
 * Method:    test
 * Signature: (Ljava/lang/String;I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_serialport_PsamSerialPort_test
  (JNIEnv *, jclass, jstring, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
